## Step 1:  Importing the libraries

In [ ]:
import numpy as np
import pandas as pd

## Step 2:Importing dataset

In [ ]:
dataset = pd.read_csv('ShopSellData.csv')
X = dataset.iloc[ : , :-1].values
Y = dataset.iloc[ : , 3].values

In [ ]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [ ]:
#Finding shapes of the X and Y
print(f'Shape of X is {X.shape}')
print(f'Shape of Y is {Y.shape}')

Shape of X is (10, 3)
Shape of Y is (10,)


In [ ]:
X # print X values

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
Y # print y values

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## Step 3: Handling the missing data

In [ ]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[ : , 1:3])
X[ : , 1:3] = imputer.transform(X[ : , 1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## Step 4: Encoding categorical data

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[ : , 0] = labelencoder_X.fit_transform(X[ : , 0])
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [ ]:
# encode your Y values as well
labelencoder_Y = LabelEncoder()
Y =  labelencoder_Y.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## Step 5: Splitting the datasets into training sets and Test sets

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split( X , Y , test_size = 0.2, random_state = 10)

print("**********************")
print(f'shape of X_train:{X_train.shape}')
print(f'shape of X_test:{X_test.shape}')
print("**********************")
print(f'shape of Y_train:{Y_train.shape}')
print(f'shape of Y_test:{Y_test.shape}')
print("**********************")

**********************
shape of X_train:(8, 3)
shape of X_test:(2, 3)
**********************
shape of Y_train:(8,)
shape of Y_test:(2,)
**********************


In [ ]:
X_train

array([[0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [2, 38.0, 61000.0],
       [2, 27.0, 48000.0],
       [0, 44.0, 72000.0],
       [0, 48.0, 79000.0],
       [1, 40.0, 63777.77777777778],
       [0, 37.0, 67000.0]], dtype=object)

## Step 6: Feature Scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler
minmax_X = MinMaxScaler()
X_train = minmax_X.fit_transform(X_train)
X_test = minmax_X.fit_transform(X_test)

X_train

array([[0.        , 0.38095238, 0.32258065],
       [1.        , 0.56084656, 0.12903226],
       [1.        , 0.52380952, 0.41935484],
       [1.        , 0.        , 0.        ],
       [0.        , 0.80952381, 0.77419355],
       [0.        , 1.        , 1.        ],
       [0.5       , 0.61904762, 0.50896057],
       [0.        , 0.47619048, 0.61290323]])

In [ ]:
X_test

array([[0., 1., 1.],
       [0., 0., 0.]])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)

X_train

array([[-0.94387981, -0.59788085, -0.48214934],
       [ 1.21355975,  0.05261351, -1.11141978],
       [ 1.21355975, -0.0813118 , -0.16751412],
       [ 1.21355975, -1.97539832, -1.53093341],
       [-0.94387981,  0.95182631,  0.98614835],
       [-0.94387981,  1.64058505,  1.7202972 ],
       [ 0.13483997,  0.26306757,  0.12381479],
       [-0.94387981, -0.25350148,  0.46175632]])